services:

  jenkins:
    image: jenkins/jenkins:lts
    container_name: sso-jenkins
    restart: unless-stopped
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      - sso-network

volumes:
  jenkins_data:

networks:
  sso-network:
    external: true
    name: sso-network    # réseau créé par infra/docker-compose.yml
